### ISSUE TITLE
security

### ISSUE THREAD

**Issue by benwaffle** [joshgrib/course-scheduler#32]
I just took the md5 of `admin_secret` and put that for `pass_hash`

``` bash
$ curl -v -b "pass_hash=5ebe2294ecd0e0f08eab7690d2a6ee69" -d "admin_secret=secret&course_name=hacked&lecture_info=&recitation_info=&homework_info=&exams_info=&final_info=" http://www.sitstuff.com/add_course
```

**Comment by joshgrib** [comment]
@benwaffle Maybe fixed now? Password still stored as md5 hashed, but as a global variable on the server instead of client-side. So there's no cookie to get the hashed password from (08e4711)
Thanks for helping out!

**Comment by benwaffle** [comment]
It works. You should still probably just revert to the password thing, the email part is unnecessary. (The only issue was lack of checks in `add_course` and `edit_course`). And instead of a global variable, you should generally use [sessions](https://pythonhosted.org/Flask-Session/).

**Comment by joshgrib** [comment]
Ok, I'll go back to a password in a file, and I'll look into sessions too
